### ISSUE TITLE
Syntax Highlighting No longer working in 5.2 version

### ISSUE THREAD

**Issue by AlNotAlbert** [arianrhodsandlot/devdocs-web-ext#40]
![f82380c38457c56b0b0adc3fa8b3f0ad](https://user-images.githubusercontent.com/87888006/232397946-b5fa3982-61f9-405c-8961-4ae611af85b0.png)

**Comment by arianrhodsandlot** [comment]
It seems that the issue is caused by the migration from devdocs' Prismjs to npm's Prismjs. 

before:
https://github.com/arianrhodsandlot/devdocs-web-ext/blob/5768320bbfa58fcbb9512e90e5a85cfd7a1049ce/src/popup/index.tsx#L5

after:
https://github.com/arianrhodsandlot/devdocs-web-ext/blob/d9a8e2ac62cf57a9a2f62ff63b5338775aa2d939/src/pages/popup/components/content.tsx#L5

However, the latter does not support Rust by default.

I will address this issue promptly and make the necessary fixes. Thank you for your feedback.
